### PR TITLE
support :stream

### PR DESCRIPTION
**Pull request by ayrat555**
This PR adds support of standard streams

### CODE REVIEW

**Comment by ayrat555** [comment]
@ericentin hi! Thanks for the library. Can you please review this PR and release a new version if it's ok?

**Comment by ericentin** [comment]
@ayrat555 thanks for the PR! This seems like something I would like to include, will review more closely when I get a chance.

**Comment by ericentin** [comment]
Looks pretty good! Going to merge, make a couple minor updates, and then release. Thanks again for your contribution!

**Comment by ayrat555** [comment]
@ericentin can you please release a new version?

**Comment by ericentin** [comment]
Hey @ayrat555, in the process of doing my updates, I realized your implementation of streams doesn't fit some of the expectations I believe Elixir users have for streams.

The biggest issues I have are the requirement to manually close the stream server, and that the stream itself cannot be used again. For instance, in the standard library, `IO.Stream` and `File.Stream` both manage the underlying resource, and do not refer to a single "open" resource, instead containing the information necessary to open a new "resource" and stream the results each time the stream is enumerated.

My first thought on how to resolve this and still provide a streaming interface would be to have a new `:stream` option alongside `:sync`, which would look a lot like `:sync`, except instead of running the process and waiting for it to end, it would return a new `Exexec.Stream` struct which would contain all the passed arguments for `run`/`run_link`, which would wait for enumeration to begin to actually invoke `:erlexec`. The stream would then enumerate through process "events" such as the process starting, stdout/stderr lines, and eventually process terminated.

Obviously, this represents a significant departure from your original implementation. 

I took a look at how you use Exexec in your project, and I actually think your project may actually be better served by using the `{:stdout | :stderr, fn io_stream, os_pid, data -> ... end}` option which already exists, or by just having your test process receive the data itself using `{:stdout | :stderr, self()}`. Currently, your streaming implementation relies on the stream being partially enumerable and keeping state, which I believe breaks stream semantics, and is closer to a callback/message passing semantics.

Happy to discuss, but this version of streaming is not currently something I want to release. Thanks again for your contribution!

**Pull request merged**
