### PR TITLE
updating erlexec to 1.6

### PR DESCRIPTION
**Pull request by torrick**
Thank you for this nice wrapper.  Latest erlexec is 1.6 so I updated the deps to use that.

### CODE REVIEW

**Comment by ericentin** [comment]
Thanks for the PR! Would love to merge as soon as the tests are fixed.

**Comment by torrick** [comment]
whoops I'll take a look at the failures.  mix test ran fine for me when I committed.

**Comment by torrick** [comment]
So tests pass but the dialyzer is complaining: 

```
$ mix dialyzer --halt-exit-status
Starting Dialyzer
dialyzer --no_check_plt --plt .dialyxir/.local.plt -Wunmatched_returns -Werror_handling -Wrace_conditions -Wunderspecs /home/travis/build/antipax/exexec/_build/test/lib/exexec/ebin
  Proceeding with analysis...
exexec.ex:90: Type specification 'Elixir.Exexec':manage(os_pid() | port()) -> {'ok',pid(),os_pid()} | {'error',any()} is a supertype of the success typing: 'Elixir.Exexec':manage(port() | non_neg_integer()) -> {'error','not_found' | [{_,_},...]} | {'ok',pid(),non_neg_integer()}
 done in 0m1.39s
done (warnings were emitted)
```

I can take a look unless that is something you would prefer handling yourself.  I didn't change any of the actual code.  Just the mix.exs and travis.yml

**Comment by torrick** [comment]
I got the dialyzer to behave but it took quite a bit of updating to do so.  Various dependencies have been updated and I had to update some of the dialyzer configurations.  But everything ran successfully on my travis build with the exception of the coveralls.

**Pull request merged**
